image: node:22

stages:
  - install
  - test
  - deploy

cache:
  paths:
    - node_modules/

install_dependencies:
  stage: install
  script:
    - corepack enable && yarn install
    - yarn lint

test:
  stage: test
  script:
    - corepack enable && yarn test:coverage
  except:
    - main

deploy-dev:
  stage: deploy
  script:
    - npm install -g serverless
    - npx sls export-env --stage dev && sls deploy --stage dev
  only:
    - development

deploy-prod:
  stage: deploy
  script:
    - npm install -g serverless
    - npx sls export-env --stage dev &&  deploy --stage prod
  only:
    - main
